cargo-features = ["profile-rustflags"]

[package]
name = "avoid_false_positives"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
alohomora = { path = "../../alohomora" }
dependency = { path = "../dependency" }
#serde = { version = "=1.0.196", features = ["derive"] } 