use alohomora::pcr::{PrivacyCriticalRegion, Signature};

//TODO changing these values doesn't invalidate the signature

const NUM: u8 = 2; 
static STATIC_NUM: u8 = 4; 

fn main() {
    static_fn(); 
    constant_fn(); 
}

fn static_fn() {
    let _static_pcr = PrivacyCriticalRegion::new(|x: u8| { println!("{}", x + STATIC_NUM) },
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUJrWm1SN05IaVpueXEyeDJ3QjFiLy9QWk5ndzlQbXo5VlVjakNMUmFKejhkK211U3I1L2t4OTNPbFQ1eUZUK1kKZDFvNTFqdGppVDZjNmgwR0wrZ2JRTAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUJrWm1SN05IaVpueXEyeDJ3QjFiLy9QWk5ndzlQbXo5VlVjakNMUmFKejhkK211U3I1L2t4OTNPbFQ1eUZUK1kKZDFvNTFqdGppVDZjNmgwR0wrZ2JRTAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURxRW9Wam1CUFRCaWtBdzlHS2JqUi9TL2s2bDJYUXZtT2JMdzNEU1pBak9HcTBIL3BBTmJCYlBJb0FaaGZMSnIKT3RmdEpBa255dWRwWjR4ZWZlR2Q0RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"});  
}

fn constant_fn(){
    let _const_pcr = PrivacyCriticalRegion::new(|x: u8| { println!("{}", x + NUM) },
    Signature {username: "corinnt", 
        signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUErMFpVTjRvdVdUUmc1eEJxREVsd0JPdjU1SkJOM2JqQndzcVpGaHFzV3k0dWwxOXk5SVdBZkxXR0g5aTlRZy8KVFA5TFcyQ0pwcFFBN25pRlRyY3ZBUAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
    Signature {username: "corinnt", 
        signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUErMFpVTjRvdVdUUmc1eEJxREVsd0JPdjU1SkJOM2JqQndzcVpGaHFzV3k0dWwxOXk5SVdBZkxXR0g5aTlRZy8KVFA5TFcyQ0pwcFFBN25pRlRyY3ZBUAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
    Signature {username: "corinnt", 
        signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURxRW9Wam1CUFRCaWtBdzlHS2JqUi9TL2s2bDJYUXZtT2JMdzNEU1pBak9HcTBIL3BBTmJCYlBJb0FaaGZMSnIKT3RmdEpBa255dWRwWjR4ZWZlR2Q0RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"});  
}
