use alohomora::pcr::{PrivacyCriticalRegion, Signature};
use dependency::external_math; 

fn _other_fn(){
    println!("I'm also another function");
}

fn call_external_math(left: u8, right: u8) -> u8 {
    external_math(left, right)
}

fn main() {
    let _pcr0 = PrivacyCriticalRegion::new(|x: u8| { 
        call_external_math(x, x) 
    }, 
    Signature {username: "corinnt", 
        signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUFPRXdxeS9tc3FzUVo1ak05YnI0dzd6eWRiamplMGZRM2RncUFyNjVwNHNCWFN5QWhxZjBRS3RGeWl4UlJ5RUoKdDAvUkczRDNmYWZESXVrbFc1amE4RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
    Signature {username: "corinnt", 
        signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUFPRXdxeS9tc3FzUVo1ak05YnI0dzd6eWRiamplMGZRM2RncUFyNjVwNHNCWFN5QWhxZjBRS3RGeWl4UlJ5RUoKdDAvUkczRDNmYWZESXVrbFc1amE4RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"},
    Signature {username: "corinnt", 
        signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUNNc24yYVluZTdINkQ3OENYR3Y0c3EveENKVGpSMTBDK3ZRYkZLTUhJK2tXNmlvQUZ4NXFpU2FLeXExNmFKaEUKZHpVcHVGeFZBb2tIT011d0czTitvTAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}); 
}

fn _other_fn2(){
    println!("I'm another function");
}
