use alohomora::pcr::{PrivacyCriticalRegion, Signature};
use crate::second::child; 

mod second;
mod third; 
// changing the function from mod third (called in second::child) invalidates the signature
fn main() {
    let _pcr = PrivacyCriticalRegion::new(|x: u8| { x + child(x) },
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUFnWXhDYWJPNlk3eUVmS0g5VHI1aEFwT1hHQ00rSHhlWDdzQkU3b0QyUlljVG1tYkltdGd2TjgrTlUyUXpRZEEKZG0xa0Z3RG9KNVVLNFEzM1pCR1lRRwotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUFnWXhDYWJPNlk3eUVmS0g5VHI1aEFwT1hHQ00rSHhlWDdzQkU3b0QyUlljVG1tYkltdGd2TjgrTlUyUXpRZEEKZG0xa0Z3RG9KNVVLNFEzM1pCR1lRRwotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"},
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURxRW9Wam1CUFRCaWtBdzlHS2JqUi9TL2s2bDJYUXZtT2JMdzNEU1pBak9HcTBIL3BBTmJCYlBJb0FaaGZMSnIKT3RmdEpBa255dWRwWjR4ZWZlR2Q0RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}); 
}