use alohomora::pcr::{PrivacyCriticalRegion, Signature};

fn main(){
    let plus_two = |x: u8| { x + 2 };
      
    fn plus_2(x: u8) -> u8 { x + 2 } 

    let _pcr = PrivacyCriticalRegion::new(|x: u8| { plus_two(x) + plus_2(x)},
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUI5TVVpa29XUi9ERzA5cWpGcHdhWjFWWGNtc1pobk1sci9wNGlPb2ZjQmhoNEZhd2VQWmZJblFPdUQ3cXArVFkKeFBBTVB4QkJab2crTUZ5a1FlU1hJTAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUI5TVVpa29XUi9ERzA5cWpGcHdhWjFWWGNtc1pobk1sci9wNGlPb2ZjQmhoNEZhd2VQWmZJblFPdUQ3cXArVFkKeFBBTVB4QkJab2crTUZ5a1FlU1hJTAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"},
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURxRW9Wam1CUFRCaWtBdzlHS2JqUi9TL2s2bDJYUXZtT2JMdzNEU1pBak9HcTBIL3BBTmJCYlBJb0FaaGZMSnIKT3RmdEpBa255dWRwWjR4ZWZlR2Q0RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}); 
}







