use alohomora::pcr::{PrivacyCriticalRegion, Signature};

fn main() {
    copy_fn_to_dependencies();
    copy_between_fns();
  
}

fn copy_between_fns() {
    let _pcr = PrivacyCriticalRegion::new(|x: u8| { x + 1  },
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUR4Rzg4RnNjSW8xWERJKytUTlJUdGRGTXFBVUxCTmlBd1B1SWxYZmZtUjRZWHVpUTR4ZkY0R3ptTGdEeHZ4aUYKRHdEZlJWdzdPOVFJdXcrNVhlTEdVRAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUR4Rzg4RnNjSW8xWERJKytUTlJUdGRGTXFBVUxCTmlBd1B1SWxYZmZtUjRZWHVpUTR4ZkY0R3ptTGdEeHZ4aUYKRHdEZlJWdzdPOVFJdXcrNVhlTEdVRAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"},  
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURxRW9Wam1CUFRCaWtBdzlHS2JqUi9TL2s2bDJYUXZtT2JMdzNEU1pBak9HcTBIL3BBTmJCYlBJb0FaaGZMSnIKT3RmdEpBa255dWRwWjR4ZWZlR2Q0RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}); 

    let _pcr2 = PrivacyCriticalRegion::new(|x: u8| { 
                //copy a fn review signature to different PCR
                x + 2 },
                Signature {username: "corinnt", // copied signature from _pcr
                    signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUR4Rzg4RnNjSW8xWERJKytUTlJUdGRGTXFBVUxCTmlBd1B1SWxYZmZtUjRZWHVpUTR4ZkY0R3ptTGdEeHZ4aUYKRHdEZlJWdzdPOVFJdXcrNVhlTEdVRAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
                Signature {username: "corinnt",  
                    signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUR4Rzg4RnNjSW8xWERJKytUTlJUdGRGTXFBVUxCTmlBd1B1SWxYZmZtUjRZWHVpUTR4ZkY0R3ptTGdEeHZ4aUYKRHdEZlJWdzdPOVFJdXcrNVhlTEdVRAotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"},             
                Signature {username: "corinnt", 
                    signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURxRW9Wam1CUFRCaWtBdzlHS2JqUi9TL2s2bDJYUXZtT2JMdzNEU1pBak9HcTBIL3BBTmJCYlBJb0FaaGZMSnIKT3RmdEpBa255dWRwWjR4ZWZlR2Q0RgotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"});
}

fn copy_fn_to_dependencies() {
    let _pcr = PrivacyCriticalRegion::new(|x: u8| { 
        //copy fn sign to dependencies signature
        x + 1  },
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURoWnRZUVFTZzRUWDU2cUg5NjJuQnVrTU5nNDZ4c0VzczN5eTZzSm9icFlzeEtjcW0rNXRpOEpDcWg4U0crM28Ka3JtRHFaQ3RmdXJ4a2tFekgzUnhZRwotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURoWnRZUVFTZzRUWDU2cUg5NjJuQnVrTU5nNDZ4c0VzczN5eTZzSm9icFlzeEtjcW0rNXRpOEpDcWg4U0crM28Ka3JtRHFaQ3RmdXJ4a2tFekgzUnhZRwotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"},  
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRURoWnRZUVFTZzRUWDU2cUg5NjJuQnVrTU5nNDZ4c0VzczN5eTZzSm9icFlzeEtjcW0rNXRpOEpDcWg4U0crM28Ka3JtRHFaQ3RmdXJ4a2tFekgzUnhZRwotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}); 
}